exclude: >
  (?x)^(
      geoml/feature_data.py|
      geoml/feature_selection.py|
      geoml/join_tables.py|
      geoml/predict.py|
      geoml/profile_keys.py|
      geoml/tables.py|
      geoml/training.py|
      geoml/tests/|
      conftest.py
  )

repos:
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/ambv/black
  rev: 23.1.0
  rev: 23.1.0
  hooks:
    - id: black
- repo: https://github.com/pycqa/flake8
  rev: '6.0.0'
  hooks:
    - id: flake8
      exclude: (tests|doc)
      additional_dependencies: [
          'flake8-docstrings',
          'flake8-builtins',
          'flake8-logging-format',
          'flake8-rst-docstrings',
          'pygments',
          'pep8-naming'
      ]