exclude: "(?x)^(\n    geoml/feature_data.py|\n    geoml/feature_selection.py|\n    geoml/join_tables.py|\n
    \   geoml/predict.py|\n    geoml/profile_keys.py|\n    geoml/tables.py|\n    geoml/training.py|\n
    \   geoml/tests/|\n    conftest.py\n)\n"
repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        exclude: (tests|doc)
        additional_dependencies:
        - flake8-docstrings
        - flake8-builtins
        - flake8-logging-format
        - flake8-rst-docstrings
        - pygments
        - pep8-naming
