channels:
    - conda-forge
dependencies:
    - python=3.8
    - geopandas=0.8.*
    - keyring=21.1.*
    - geoalchemy2=0.6.*
    - psycopg2=2.8.*
    - rasterio=1.1.*
    - rasterstats=0.14.*
    - scikit-learn=0.23.*
    - seaborn=0.11.*
    - spectral=0.22.*
    - sqlalchemy=1.3.*
    - sqlalchemy-utils=0.36.*
    - google-cloud-storage=1.31.*
    - earthengine-api=0.1.*
    - spyder=4.1.*
    - pip=20.2.*
    - pip:
        - -r file:requirements/dev_pip.txt
