[tool.poetry]
name = "geoml"
version = "0.1.1"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
spectral = "^0.22.4"
geopandas = "^0.10.2"
rasterio = "^1.2.10"
rasterstats = "^0.16.0"
SQLAlchemy = "^1.4.31"
GeoAlchemy2 = "^0.10.2"
seaborn = "^0.11.2"
keyring = "^23.5.0"
pip = "^22.0.4"
pygeos = "^0.12.0"
Rtree = "^0.9.7"
scikit-learn = "^1.0.2"
db = {git = "git@github.com:SenteraLLC/db", rev = "to_mlops"}
ipykernel = {version = "^6.9.1", optional = true}

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"
sure = "^2.0.0"
flake8 = "^4.0.1"
pytest = "^7.0.1"
black = "^22.1.0"

[tool.poetry.extras]
ipykernel = ["ipykernel"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
